[package]
name = "georacer-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = { version = "0.8.4", features = ["ws"] }
axum_static = "1.7.1"
dashmap = "6.1.0"
mongodb = "3.3.0"
tokio = { version = "1.47.1", features = ["full"] }
